[project]
name = "parse-crypto-predictions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.2",
    "pycountry>=24.6.1",
    "pydantic-extra-types>=2.10.5",
    "uvicorn>=0.35.0",
]
